using System.Collections.Generic;

namespace LayeredCraft.SourceGeneratorTools.Generator;

internal static class GeneratorConstants
{
    internal const string GeneratedCodeHeader = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable


        """;

    internal static readonly Dictionary<string, GeneratableFeature> Features = new()
    {
        ["EquatableArray"] = new GeneratableFeature(
            "EquatableArray",
            [
                "Tools/Types/EquatableArray/EquatableArray.cs",
                "Tools/Types/EquatableArray/EquatableArrayExtensions.cs",
                "Tools/Utilities/HashCode.cs",
            ]
        ),
    };
}
